### ISSUE TITLE
在linux服务器下安装出现权限问题

### ISSUE THREAD

**Issue by XiaoDHuang** [vuejs/vue-docs-zh-cn#24]
```sh
npm install @vue/cli-plugin-unit-mocha

> nodent-runtime@3.2.1 install /root/platform-web2/node_modules/nodent-runtime
> node build.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/root/platform-web2/node_modules/nodent-runtime/dist/index.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.<anonymous> (/root/platform-web2/node_modules/nodent-runtime/build.js:5:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

```

centos中

**Comment by Jinjiang** [comment]
转述一下 @sodatea 的答复：

> 权限问题是 npm 的设计问题，在他们下个大版本中会改掉。目前只能推荐不要用 root 用户或者加 --unsafe-perm

更多 cli 问题请直接在 https://github.com/vuejs/vue-cli 谢谢

**Comment by sodatea** [comment]
一些相关资料：
https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
https://github.com/npm/rfcs/blob/latest/accepted/0012-running-as-root.md
